version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.4
jobs:
  pipenv-install:
    docker:
      - image: cimg/python:3.7
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}-v1
      - run:
          name: Install pip dependencies
          command: |
            if [[ -d ".venv" ]]; then
              echo "Virtual environment restored from cache, skipping pipenv install"
            else
              pipenv install --dev
              if [[ -n $(git diff --shortstat Pipfile.lock) ]]; then
                echo "Pipfile.lock is out of date:"
                git --no-pager diff Pipfile.lock
                exit 1
              fi
            fi
      - save_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}-v1
          paths:
            - .venv
            - integreat_cms.egg-info
            - /home/circleci/.cache/pip
            - /home/circleci/.cache/pipenv
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - integreat_cms.egg-info
  black:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check black code style
          command: pipenv run black --check .
  pylint:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run pylint
          command: pipenv run pylint_runner
  check-translations:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install translation requirements
          command: sudo apt-get update && sudo apt-get install gettext pcregrep
      - run:
          name: Check translation file for missing or empty entries
          command: ./dev-tools/check_translations.sh
  compile-translations:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install gettext
          command: sudo apt-get update && sudo apt-get install gettext
      - run:
          name: Compile translation file
          command: |
            cd integreat_cms
            pipenv run integreat-cms-cli compilemessages --settings=integreat_cms.core.circleci_settings
      - persist_to_workspace:
          root: .
          paths:
            - integreat_cms/locale/de/LC_MESSAGES/django.mo
  webpack:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}-v1
      - run:
          name: Install npm dependencies
          command: |
            if [[ -d "node_modules" ]]; then
              echo "Node modules restored from cache, skipping npm install"
            else
              npm ci
              if [[ -n $(git diff --shortstat package-lock.json) ]]; then
                echo "package-lock.json is out of date:"
                git --no-pager diff package-lock.json
                exit 1
              fi
            fi
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}-v1
          paths:
            - node_modules
      - run:
          name: Compile and bundle CSS and JS
          command: npm run prod
      - persist_to_workspace:
          root: .
          paths:
            - integreat_cms/static/dist
            - integreat_cms/webpack-stats.json
  test:
    docker:
      - image: cimg/python:3.7
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_USER: integreat
          POSTGRES_DB: integreat
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Migrate database
          command: |
            pipenv run integreat-cms-cli makemigrations cms --settings=integreat_cms.core.circleci_settings
            pipenv run integreat-cms-cli migrate --settings=integreat_cms.core.circleci_settings
      - run:
          name: Run tests
          command: pipenv run integreat-cms-cli test integreat_cms --set=COVERAGE --settings=integreat_cms.core.circleci_settings
      - store_artifacts:
          path: htmlcov
  build-package:
    docker:
      - image: integreat/bionic-setuptools:78c07dc
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Create integreat-cms package
          command: python3 setup.py --command-packages=stdeb.command bdist_deb
      - store_artifacts:
          path: dist
  build-documentation:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Generate documentation
          command: pipenv run ./dev-tools/generate_documentation.sh
      - persist_to_workspace:
          root: .
          paths:
            - docs
  deploy-documentation:
    docker:
      - image: cimg/python:3.7
    environment:
      BRANCH: gh-pages
      DOC_DIR: docs
      TMP_DIR: .gh-pages
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints: 8f:d7:a2:cb:47:e2:cf:9b:78:44:86:6d:4e:44:11:54
      - run:
          name: Add GitHub's Public SSH Key to known hosts
          command: echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: Prepare git config
          command: |
            git config --global user.name DigitalfabrikMember
            git config --global user.email 41921676+DigitalfabrikMember@users.noreply.github.com
      - run:
          name: Clone existing gh-pages branch into temporary directory
          command: git clone --depth=1 $CIRCLE_REPOSITORY_URL -b $BRANCH $TMP_DIR
      - run:
          when: on_fail
          name: Initialize gh-pages branch in new temporary git directory
          command: |
            git init $TMP_DIR
            cd $TMP_DIR
            git remote add origin $CIRCLE_REPOSITORY_URL
            git checkout -b $BRANCH
      - run:
          name: Copy documentation into temporary directory
          command: |
            rm -rfv ${TMP_DIR}/*
            cp -Rv ${TMP_DIR}/../${DOC_DIR}/. $TMP_DIR
      - run:
          name: Push documentation to GitHub Pages
          command: |
            cd $TMP_DIR
            git add --all
            git commit -m "Update documentation of commit ${CIRCLE_SHA1} [skip ci]" || true
            git push origin $BRANCH
  docker-images:
    docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: |
            if git diff --name-only HEAD~1 HEAD | grep -q .circleci/images/bionic-setuptools; then
              docker build -t integreat/bionic-setuptools:$(echo $CIRCLE_SHA1 | cut -c -7) -t integreat/bionic-setuptools:latest .circleci/images/bionic-setuptools
            fi
      - run:
          name: Push Docker images
          command: |
            if git diff --name-only HEAD~1 HEAD | grep -q .circleci/images; then
              echo $DOCKER_PASSWORD | docker login -u integreat --password-stdin
            fi
            if git diff --name-only HEAD~1 HEAD | grep -q .circleci/images/bionic-setuptools; then
              docker push integreat/bionic-setuptools
            fi

workflows:
  develop:
    jobs:
      - pipenv-install
      - webpack
      - test:
          requires:
            - pipenv-install
            - webpack
      - check-translations:
          requires:
            - pipenv-install
      - compile-translations:
          requires:
            - pipenv-install
      - build-package:
          requires:
            - webpack
            - compile-translations
      - black:
          requires:
            - pipenv-install
      - pylint:
          requires:
            - pipenv-install
      - shellcheck/check:
          dir: ./dev-tools
          external_sources: true
      - build-documentation:
          requires:
            - pipenv-install
      - deploy-documentation:
          requires:
            - build-documentation
          filters:
            branches:
              only: develop
      - docker-images:
          context: docker-hub
